### ISSUE TITLE
Boolean values being submitted as strings

### ISSUE THREAD

**Issue by whitby3001** [kushniryb/minfraud-api-v2#1]
I've been using your gem to integrate with minfraud but I found that when I set the payments/was_authorized boolean value to true I get an error from maxmind: Encountered value at /payment/was_authorized that does not meet the required constraints.

When I looked into it, I saw that .to_json gets called on all the values, which turns it into a string with value 'true'. When I tried overriding this and set it back to a boolean true before it gets submitted to maxmind, then it worked as expected with no errors.

I'm just wondering if there's another way I should be doing it?

Thanks!

**Comment by ykushnir** [comment]
Hello @whitby3001 

First of all - thanks for reporting this issue!

You were right - there were some problems with the conversion of boolean values to strings
It has been fixed in the following commit - 3c69005 

:vulcan_salute:

**Comment by kushniryb** [comment]
Hello @whitby3001

First of all - thanks for reporting this issue!

You were right - there were some problems with the conversion of boolean values to strings
It has been fixed in the following commit - 3c69005

**Comment by whitby3001** [comment]
Thanks so much, that's awesome!

David
