### ISSUE TITLE
Minfraud::ErrorHandler.inspect violates LSP

### ISSUE THREAD

**Issue by dgutov** [kushniryb/minfraud-api-v2#10]
https://en.wikipedia.org/wiki/Liskov_substitution_principle

https://ruby-doc.org/core-2.6.1/Object.html#method-i-inspect

**Comment by kushniryb** [comment]
Thank you for reporting this @dgutov 👍

**Comment by kushniryb** [comment]
Addressed via https://github.com/kushniryb/minfraud-api-v2/pull/19

**Comment by dgutov** [comment]
Thanks!
