### ISSUE TITLE
Create classes for responses?

### ISSUE THREAD

**Issue by horgh** [kushniryb/minfraud-api-v2#14]
Hi! What would you think of having this gem include classes for the various responses that the API can return? This would be similar to what other minFraud 2 libraries do. For example this is the PHP library building an Insights response object: https://github.com/maxmind/minfraud-api-php/blob/master/src/MinFraud/Model/Insights.php. Essentially what I'm thinking is to have the entire response represented by custom classes with documented attributes rather than dynamically created by hashie.

One nice thing about this would be is the gem's API documentation could include details on the particular fields in the response as well as the request. I did this recently for a GeoIP2 library, for example https://www.rubydoc.info/gems/maxmind-geoip2/MaxMind/GeoIP2/Record/City.

Another benefit could be that this gem could potentially reduce its dependencies. For example, the need for hashie might go away if it were to process the response more manually itself. Although we'd want to consider backwards compatibility.

I'd potentially be available to help with this, but I figured I'd check with you before making a larger change like I'm proposing.

Thank you!

**Comment by kushniryb** [comment]
Hello @horgh! 

Thank you so much for sharing your insights, much appreciated!

Yes, I'd have to agree with you, I think it would be better to get rid of the dynamic approach in favour of well-documented classes. We've got only three endpoints to support therefore there's little to no value offered by dynamic definition.

There's lots to do when it comes to this gem, but, alas, I lack the time required to make the necessary changes at the moment so to answer your question - yes, your contributions would be more than welcome and I can't wait to see them! 

Other than that I'll be refactoring and improving the test coverage in the upcoming months. Please let me know if those are the topics you'd be interested in 🙂

Looking forward to hearing back from you,
Regards, Yurii

**Comment by horgh** [comment]
Thank you for the encouragement :-). I will see what I can do!

Yes, I'd definitely be keen to see & help with making the gem even better! I saw your refactoring PR but have not looked at it closely. I have a couple ideas for tests to add, but you've done a great job already!

**Comment by horgh** [comment]
🎉
