### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by kushniryb** [kushniryb/minfraud-api-v2#7]
Per @dan-jensen's comment in regard to #3 
=
Hey @kushniryb. This change ^ is causing trouble for me, but I think it's actually a problem with the FaradayMiddleware gem. I'd like to know what you think.

When your gem doesn't declare hashie as a runtime dependency, my app encounters an error: "RuntimeError: missing dependency for FaradayMiddleware::Mashify: cannot load such file -- hashie/mash". My error stacktrace isn't helpful, but I've found the error must be triggered on this line in the FaradayMiddleware gem: require 'hashie/mash'. Clearly hashie is a missing dependency in my app.

FaradayMiddleware declares hashie in its Gemfile. But for my app that's useless - hashie doesn't get installed. I've found hashie will be installed, and the error fixed, in a few ways:
- Adding hashie to my app's Gemfile
- Restoring hashie to your gem's gemspec
- Adding it to the FaradayMiddleware gemspec

Obviously if hashie is a dependency of FaradayMiddleware, the ideal solution is for the dependency declaration to be functioning correctly there. Back in 2013, FaradayMiddleware was modified to move dependencies from its gemspec to its Gemfile. I think that may have been a mistake. For example, Yehuda Katz says "In general, a gem's Gemfile should contain [only] the Rubygems source and a single gemspec line." And obviously reverting it fixes the error I'm encountering. But it seems unlikely that there has been a faulty dependency declaration in FaradayMiddleware for the past 5 years. What do you think?

**Comment by horgh** [comment]
https://github.com/lostisland/faraday_middleware says "Some dependent libraries are needed only when using specific middleware:", so I think the idea is that if you use a particular piece of faraday_middleware, it's supposed to be your responsibility to declare the dependency. It seems like it'd make sense for this gem to declare a dependency on hashie given that.

**Comment by kushniryb** [comment]
@horgh Perhaps we could get rid of this dependency all-together once we've implemented https://github.com/kushniryb/minfraud-api-v2/issues/14 ?

**Comment by horgh** [comment]
Yeah, I think that'd be possible!

**Comment by horgh** [comment]
I think this one can be closed as well given #16!

**Comment by kushniryb** [comment]
Yup, two birds with one stone :)
